### ISSUE TITLE
SelectionList crashes on content overflow or resize

### ISSUE THREAD

**Issue by zdovcj** [Textualize/textual#2969] opened 2023-07-18 18:59 UTC
When using SelectionList and resizing the terminal so that the text cannot fit in the screen, the program will crash. I think it also works with OptionList.

Environment:
Textual version: 0.30.0
Python version: 3.10.8

Code to reproduce:
```python
import textual.widgets
import textual.app

class App(textual.app.App):

    def compose(self):
        yield textual.widgets.SelectionList (('random_text' * 10, 0), id='id')

if __name__ == '__main__':
    App().run()

```

The last error printed is:
```
                                                                                                             
│ /opt/homebrew/lib/python3.10/site-packages/textual/widgets/_option_list.py:749 in get_option_at_index       
│                                                                                                             
│   746 │   │   try:                                                                                          
│   747 │   │   │   return self._options[index]                                                               
│   748 │   │   except IndexError:                                                                            
│ ❱ 749 │   │   │   raise OptionDoesNotExist(                                                                 
│   750 │   │   │   │   f"There is no option with an index of {index}"                                        
│   751 │   │   │   ) from None                                                                               
│   752                                                                                                       
│                                                                                                             
│ ╭──────────── locals ────────────╮                                                                          
│ │ index = 1                      │                                                                          
│ │  self = SelectionList(id='id') │                                                                          
│ ╰────────────────────────────────╯                                                                          
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

I have tried to size my content upon resize event, but it doesn't solve the issue. In this case, it will even crash on increasing the terminal size. I assume that the function that sets the content length might be called before  the the code that crashes.

Code to reproduce the crash upon increasing:
```python
import textual.widgets
import textual.app
import textual.events
import textual  

class App(textual.app.App):

    @textual.on(textual.events.Resize)
    def resize_handler(self):
        width = self.size.width
        text = 'a' * (width - 4)
        widget = self.query_one(textual.widgets.SelectionList)
        widget.clear_options()
        widget.add_option((text, 0, None))

    def compose(self):
        yield textual.widgets.SelectionList (('random_text', 0), id='widget_id')

if __name__ == '__main__':
    App().run()
```

**Comment by davep** [comment] 2023-07-18 19:01
Thanks. That looks to be a duplicate of #2900 so I'll close this in favour of the earlier report.

**Closed by davep** 2023-07-18 19:01 UTC

**Comment by zdovcj** [comment] 2023-07-18 19:13
Ok. Sorry for not noticing and posting a duplicate. I will at least add the code that dynamically changes the content length to #2900.

**Comment by davep** [comment] 2023-07-18 19:15
> Sorry for not noticing and posting a duplicate

Absolutely no need to apologise; it's not always simple to find other issues and we'd sooner have a duplicate report than no report at all! :-)
