### ISSUE TITLE
Document handler names for events

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1590] opened 2023-01-17 11:47 UTC
Currently there is no place in the docs where the handler name is explicitly shown. It has to be deduced, and it's easy to make mistakes.

We should add the handler name to a section in the docs.

For instance [this page](https://textual.textualize.io/widgets/directory_tree/) should document that the handler name is `on_directory_tree_file_selected`.

BTW If you have a event or messages you can inspect the `handler_name` property.

**Comment by davep** [comment] 2023-01-17 13:10
Duplicate of #1568.

**Closed** 2023-01-30 15:52 UTC
Labels: documentation, Task
