### ISSUE TITLE
Investigate cursor issue for CJK input

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3404] opened 2023-09-26 10:32 UTC
Currently it is difficult (impossible?) to enter CJK text in Input or TextArea, due to the terminal cursor not being where our self-draw cursor is.

I think we may be able to restore the default behaviour, by moving the terminal cursor back to the input after every update.

We need to investigate how to achieve this, and if there is any other work we need to do to allow seamless CJK text entry.

**Comment by darrenburns** [comment] 2023-09-26 10:33
Related/duplicate of #1469

**Closed** 2023-10-05 14:41 UTC
