### ISSUE TITLE
Textual console showing wrong path

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3237] opened 2023-09-05 13:21 UTC
The `textual console` command is showing the wrong path.

IIRC there is an offset in the stack which it uses to find the caller. We may have introduced another level in the stack.

![Image](https://user-images.githubusercontent.com/554369/265711686-ced5cd82-6baf-426d-957a-8d30f35cb9c2.png)

**Comment by davep** [comment] 2023-09-13 10:00
On initial look at this, I don't think the issue is as broad as is suggested here. Given this code:

```python
from textual import on
from textual.app import App, ComposeResult
from textual.widgets import Button

class LogLocationApp(App[None]):

    def compose(self) -> ComposeResult:
        yield Button("Print", id="print")
        yield Button("Log", id="log")

    @on(Button.Pressed, "#print")
    def print_to_console(self) -> None:
        print("This was from a print")

    @on(Button.Pressed, "#log")
    def log_to_console(self) -> None:
        self.log.debug("This was from a log")

if __name__ == "__main__":
    LogLocationApp().run()
```

I see a variety of locations that mostly look okay:

![Screenshot 2023-09-13 at 10 59 02](https://github.com/Textualize/textual/assets/28237/fd3f2a78-6e90-45dd-9e5a-46b5426dba48)

Presumably the thing that's the issue here is when something is logged to the console via `print`?

**Comment by davep** [comment] 2023-09-13 10:10
Looks like the change was brought in with the capture print facility: 4406b9d608ec2e8137fb8c77fef643b52471bd43

**Comment by willmcgugan** [comment] 2023-09-25 08:58
@davep What's the resolution here? It's in For Review, but no linked PR.

**Comment by davep** [comment] 2023-09-25 09:01
The description of the PR linked just above (#3294) has the explanation. I believe @darrenburns reviewed the `textual-dev` side of things late last week, and moving this on was predicated on that being reviewed, accepted and deployed.

**Comment by willmcgugan** [comment] 2023-09-25 09:27
Can you please make that happen, and ping me when you need something deployed.

**Comment by davep** [comment] 2023-09-25 09:49
Reopening for a moment (GitHub helpfully closed it when I merged the PR on `textual-dev`).

@willmcgugan `textual-dev` should now be ready to deploy (with an appropriate version bump, of course), so things can then move forward.

**Closed** 2023-10-05 15:00 UTC
Labels: bug, Task
