### ISSUE TITLE
`Tabs` still has active tab after cleared

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3523] opened 2023-10-12 18:44 UTC
The docs say that `Tabs.Cleared` is sent "when there are no active tabs", but this raises an assertion error

```python
from textual.app import App, ComposeResult
from textual.widgets import Footer, Tab, Tabs


class TabsApp(App):
    BINDINGS = [("space", "clear_tabs", "Clear tabs")]

    def compose(self) -> ComposeResult:
        yield Tabs(
            Tab("First tab", id="one"),
            Tab("Second tab", id="two"),
        )
        yield Footer()

    def on_tabs_cleared(self, event: Tabs.Cleared) -> None:
        assert not event.tabs.active, f"{event.tabs.active} should not be!"

    def action_clear_tabs(self) -> None:
        self.query_one(Tabs).clear()


if __name__ == "__main__":
    app = TabsApp()
    app.run()
```

[Edited to correct code example: I always mix up active and active_tab!]

**Comment by TomJGooding** [comment] 2023-10-12 20:05
After some further testing, I found that `Tabs.active` doesn't seem to account for any removal of tabs.

```python
from textual.app import App, ComposeResult
from textual.widgets import Footer, Log, Tab, Tabs


class TabsApp(App):
    BINDINGS = [
        ("space", "clear_tabs", "Clear tabs"),
        ("x", "remove_current_tab", "Remove current tab"),
        ("l", "log_active_tab", "Log current tab"),
    ]

    def compose(self) -> ComposeResult:
        yield Tabs(
            Tab("First tab", id="one"),
            Tab("Second tab", id="two"),
        )
        yield Log()
        yield Footer()

    # def on_tabs_cleared(se2yylf, event: Tabs.Cleared) -> None:
    #     assert not event.tabs.active, f"{event.tabs.active} should not be!"

    def action_clear_tabs(self) -> None:
        self.query_one(Tabs).clear()

    def action_remove_current_tab(self) -> None:
        tabs = self.query_one(Tabs)
        tabs.remove_tab(tabs.active)

    def action_log_active_tab(self) -> None:
        tabs = self.query_one(Tabs)
        log = self.query_one(Log)
        log.write_line(tabs.active)


if __name__ == "__main__":
    app = TabsApp()
    app.run()
```

**Comment by darrenburns** [comment] 2023-10-12 20:33
My current "flaky tests" PR has a fix for this I think.

**Comment by TomJGooding** [comment] 2023-10-12 20:52
I think this might be a wider problem with how the active tab is handled.

I'm seeing the same results after:

pip install git+https://github.com/textualize/textual.git@flaky-tests#egg=textual

**Comment by darrenburns** [comment] 2023-10-12 21:07
Sorry yeah, my "fix" is incomplete/wip at the moment but I should hopefully resolve it on Monday.

There's definitely a race condition where the active tab isn't being reassigned immediately after removal - it's done after refresh. I'm resolving by making "remove_tab" awaitable. As you said though it may be a broader issue - but the root cause could be the race. I'll try to check this out on Monday and see if it's related

**Comment by darrenburns** [comment] 2023-10-16 19:35
Should be fixed in my PR now. It was a wider problem than just the race-condition - `Tabs.active` simply wasn't being assigned in `remove_tab` or `clear`.

**Comment by TomJGooding** [comment] 2023-10-16 19:55
Thanks Darren for the update. Possibly this fix might help resolve #3412 as well.

**Comment by darrenburns** [comment] 2023-10-17 10:41
Good catch - it may! Will test it out shortly.

**Comment by darrenburns** [comment] 2023-10-17 12:17
Tested it out - looks like my PR doesn't resolve #3412 by itself.

**Closed** 2023-10-25 13:41 UTC
