### ISSUE TITLE
Pushing a screen on the app's `on mount` method breaks the main screen graphically

### ISSUE THREAD

**Issue by dmunozv04** [Textualize/textual#3221] opened 2023-09-01 18:27 UTC
I instantly push a screen with the app's `on_mount` method and after popping it, the checkbox doesn't display properly. It also seems to happen with other elements on more complex layouts. It looks like they display as disabled on other terminals, though they don't even show on windows terminal.
Code and video attached.

video: https://github.com/Textualize/textual/assets/39565245/54559531-a0c4-4198-97b3-8e9a6d7a79bc

Code: 
```Python
from textual import on
from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.screen import Screen, ModalScreen
from textual.widgets import Label, Button, Checkbox


class BugScreen(ModalScreen):
    DEFAULT_CSS = """
    BugScreen {
    }
    #bug-container {
    }
    
    """

    def compose(self) -> ComposeResult:
        with Vertical(id="bug-container"):
            yield Label("This is a screen")
            yield Button("Press me to close screen", name="button")

    @on(Button.Pressed)
    def close_screen(self, event: Button.Pressed):
        self.app.pop_screen()


class BugApp(App):
    def compose(self) -> ComposeResult:
        yield Button("Demo button", name="button")
        yield Label("This is the main screen")
        yield Checkbox("This is a checkbox", name="checkbox")

    def _on_mount(self) -> None:
        self.push_screen(BugScreen())


if __name__ == "__main__":
    app = BugApp()
    app.run()
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.35.1 |
| Rich    | 13.4.2 |

## Python

| Name           | Value                                                               |
|----------------|---------------------------------------------------------------------|
| Version        | 3.11.3                                                              |
| Implementation | CPython                                                             |
| Compiler       | MSC v.1934 64 bit (AMD64)                                           |
| Executable     | C:\Users\someone\somewhere\venv\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.22621 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=188, height=49 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 188                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 49                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by davep** [comment] 2023-09-01 21:56
Just to note, this seems to be an issue with composing from the app into the main screen. A variation on the above that uses its own screen rather than the default screen seems to work as intended:

```python
from textual import on
from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.screen import Screen, ModalScreen
from textual.widgets import Label, Button, Checkbox


class BugScreen(ModalScreen):
    DEFAULT_CSS = """
    BugScreen {
    }
    #bug-container {
    }

    """

    def compose(self) -> ComposeResult:
        with Vertical(id="bug-container"):
            yield Label("This is a screen")
            yield Button("Press me to close screen", name="button")

    @on(Button.Pressed)
    def close_screen(self):
        self.app.pop_screen()


class MainScreen(Screen):

    def compose(self) -> ComposeResult:
        yield Button("Demo button", name="button")
        yield Label("This is the main screen")
        yield Checkbox("This is a checkbox", name="checkbox")

    def on_mount(self) -> None:
        self.app.push_screen(BugScreen())


class BugApp(App):

    def on_mount(self) -> None:
        self.push_screen(MainScreen())


if __name__ == "__main__":
    BugApp().run()
```

**Comment by dmunozv04** [comment] 2023-09-01 22:44
@davep thanks for the workaround, I'll be interested to see what caused the bug.

**Comment by willmcgugan** [comment] 2023-09-02 08:17
Should be fixed by https://github.com/Textualize/textual/pull/3218

**Comment by dmunozv04** [comment] 2023-09-02 21:36
@davep I just tried the example code you posted, and it still gives a wrong output on windows terminal, looking identical to my first video

**Closed** 2023-09-04 09:53 UTC
Labels: bug, Task
