### ISSUE TITLE
Japanese text input is not rendered inline

### ISSUE THREAD

**Issue by crftwr** [Textualize/textual#1469] opened 2023-01-02 21:20 UTC
> Sorry if this is a known issue.

I tried to input Japanese characters on "textual" demo app, and found that Textual app doesn't render IME text / list at expected place.

When typing Japanese characters (and probably other many non-English languages also), applications are expected to render IME text and candidate word list, with the help of the OS. And the position of the text and list should be the caret position in the text input widget.

I tested this only on Mac OS (Ventura 13.0.1), but I will check the same on Windows OS later and update this report.

Please see attached screenshots.

**Textual app on Terminal app (unexpected behavior)**
<img width="1001" alt="screenshot1" src="https://user-images.githubusercontent.com/4488402/210277702-1b6410a1-246b-4a77-a257-153ecd27428b.png">

**Memo app (expected behavior)**
<img width="649" alt="screenshot2" src="https://user-images.githubusercontent.com/4488402/210277706-05f8b33f-276a-4c7c-a786-ce1ac5314686.png">

**Terminal app (expected behavior)**
<img width="631" alt="screenshot3" src="https://user-images.githubusercontent.com/4488402/210277940-0ce38013-d6fe-4f15-a406-4c1c14f61d78.png">

**Comment by darrenburns** [comment] 2023-01-04 09:41
This is a good point - I noticed the same thing with Japanese input.

The issue is that Textual hides the terminal cursor and uses its own "virtual" cursor.

The dropdown appears at the terminal cursor's position, which is at the bottom right of the widget (since the full widget repaints from top left to bottom right).

It seems some TUI apps use the terminal cursor though, so the dropdown appears in the correct position. For example, vim and mc seem fine.

It'll require more research from us, but we definitely acknowledge the issue - thank you for the report!

**Comment by crftwr** [comment] 2023-01-05 08:41
@darrenburns , thank you for your comment and aknowledgement!

**Comment by Lvdi** [comment] 2023-05-29 04:28
@darrenburns 
Hi, is there any plan for fixing this issue (or some hacky workaround)?
It's kind of a dealbreaker for creating IME-aware apps using Textual...

**Comment by 1dancook** [comment] 2023-09-20 23:10
Came to post about this issue but it's already here thankfully. Hopefully there is a fix soon for this. Thanks for all your hard work!

**Comment by darrenburns** [comment] 2023-09-26 15:50
I'm working on a fix for this now. It should hopefully completely fix the IME issue for both `Input` and `TextArea` widgets. IME will stay aligned with the cursor in both of these widgets.

**Preview:**

<img width="700" alt="image" src="https://github.com/Textualize/textual/assets/5740731/7756fcb8-f94f-470b-987a-771c10646370">

It also fixes the OS emoji pop-up which had the same problem.

**Comment by 1dancook** [comment] 2023-09-26 21:19
> I'm working on a fix for this now. It should hopefully completely fix the IME issue for both `Input` and `TextArea` widgets. IME will stay aligned with the cursor in both of these widgets.
> 
> 
> 
> **Preview:**
> 
> 
> 
> <img width="700" alt="image" src="https://github.com/Textualize/textual/assets/5740731/7756fcb8-f94f-470b-987a-771c10646370">
> 
> 
> 
> It also fixes the OS emoji pop-up which had the same problem.
> 
> 

That's awesome. I don't think I have time this week to check that out and give it a run for its money but I'm looking forward to the change! どうも！

**Closed** 2023-10-05 14:41 UTC

**Comment by darrenburns** [comment] 2023-10-05 16:06
This is merged into `main` and will be available in the next Textual release.
