### ISSUE TITLE
Mounting duplicate widget IDs can result in a `NoScreen` error

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2863] opened 2023-06-29 15:33 UTC
I'm writing this one up near the end of the day, at the start of a holiday, just so it's written down and I/we don't forget. Annoyingly I *can't* recreate the problem in isolation, only in the code I'm working on at the moment.

It is possible to get into a situation where an attempt to `mount` a widget with an ID that already exists amongst its would-be siblings results in a `NoScreen` error being thrown from somewhere deep in the compositor code rather than the `DuplicateIds`, which is what you'd expect.

The error I was seeing is follows at the end of here.

Quick testing suggests that `NodeList._append` and `NodeList._insert` are the issue here. Making a change akin to this:

```diff
@@ -74,12 +74,12 @@ class NodeList(Sequence["Widget"]):
             widget: A widget.
         """
         if widget not in self._nodes_set:
-            self._nodes.append(widget)
-            self._nodes_set.add(widget)
             widget_id = widget.id
             if widget_id is not None:
                 self._ensure_unique_id(widget_id)
                 self._nodes_by_id[widget_id] = widget
+            self._nodes.append(widget)
+            self._nodes_set.add(widget)
             self._updates += 1
 
     def _insert(self, index: int, widget: Widget) -> None:
```

seems to address the issue.

If I can work out an isolated reproduction of this I'll add it here, but the above change does seem to make some sense I think.

```
...
│                                                                                                                                                                       │
│ /Users/davep/develop/python/textual/src/textual/dom.py:477 in screen                                                                                                  │
│                                                                                                                                                                       │
│    474 │   │   while node is not None and not isinstance(node, Screen):                                                                                               │
│    475 │   │   │   node = node._parent                                                                                                                                │
│    476 │   │   if not isinstance(node, Screen):                                                                                                                       │
│ ❱  477 │   │   │   raise NoScreen("node has no screen")                                                                                                               │
│    478 │   │   return node                                                                                                                                            │
│    479 │                                                                                                                                                              │
│    480 │   @property                                                                                                                                                  │
│                                                                                                                                                                       │
│ ╭───────────────────────────────────── locals ──────────────────────────────────────╮                                                                                 │
│ │   node = None                                                                     │                                                                                 │
│ │ Screen = <class 'textual.screen.Screen'>                                          │                                                                                 │
│ │   self = RightAlignToast(id='textual-toast-91b49506-d61a-4698-ac8b-5bc491fdd5c9') │                                                                                 │
│ ╰───────────────────────────────────────────────────────────────────────────────────╯                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NoScreen: node has no screen
```

**Comment by davep** [comment] 2023-07-18 14:23
I've just spent about 40 minutes trying to isolate this error (something not made any easier by not actually having the non-isolated code easily to hand as that was an earlier incarnation of the notification code) and have utterly failed. I'm not overly keen on fixing something for which a test can't be constructed.

Should we blindly apply the suggested fix, knowing that it doesn't break existing functionality/tests? Or should we backlog this until such a time as we manage to recreate this error again?

**Comment by davep** [comment] 2023-07-19 07:24
We had wondered if it might be down to the fast removal and then mounting of widgets in the same location in the DOM, but attempting to recreate that didn't come to anything too.

Moving this to "blocked" for the moment; it would be best to fix this knowing what we're actually fixing. Meanwhile, if anyone gets the error reported at the start: let me know!

**Comment by maxking** [comment] 2023-07-20 14:10
I am seeing the same issue working on https://github.com/maxking/archive_reader.

I was relying on `DuplicateIds` to not having to check if I am adding dupe widgets, but I am seeing this error here, which results in the error:

https://github.com/maxking/archive_reader/blob/main/src/archive_reader/app.py#L370-L373

**Comment by rodrigogiraoserrao** [comment] 2023-11-21 16:18
This has been around for a while and we can't seem to reproduce it regardless of how hard we try.
We agreed to close this for now; maybe it's been fixed as a consequence of other changes we made in the past 5 months.

**Closed by rodrigogiraoserrao** 2023-11-21 16:18 UTC
Labels: bug, Task, Can not reproduce
