### ISSUE TITLE
Up and down keys don't appear in Footer

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#2219] opened 2023-04-05 16:19 UTC
If you have bindings which use the keys `up` or `down`, they don't appear in the footer.

Example:

```python
from textual.app import App, ComposeResult
from textual.binding import Binding
from textual.widgets import Footer


class Example(App):
    BINDINGS = [
        Binding("up", description="Up", action="up"),
        Binding("down", description="Down", action="down", priority=True),
    ]

    def compose(self) -> ComposeResult:
        yield Footer()


app = Example()
if __name__ == '__main__':
    app.run()

```

When you run the app, the `Footer` widget contains no content.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.17.3 |
| Rich    | 13.3.3 |

## Python

| Name           | Value                                                                                               |
|----------------|-----------------------------------------------------------------------------------------------------|
| Version        | 3.10.8                                                                                              |
| Implementation | CPython                                                                                             |
| Compiler       | Clang 14.0.0 (clang-1400.0.29.102)                                                                  |
| Executable     | /Users/darrenburns/Library/Caches/pypoetry/virtualenvs/textual-questions-mTRhYy7u-py3.10/bin/python |

## Operating System

| Name    | Value                                                                                             |
|---------|---------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                            |
| Release | 21.6.0                                                                                            |
| Version | Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 |

## Terminal

| Name                 | Value              |
|----------------------|--------------------|
| Terminal Application | iTerm.app (3.4.16) |
| TERM                 | xterm-256color     |
| COLORTERM            | truecolor          |
| FORCE_COLOR          | *Not set*          |
| NO_COLOR             | *Not set*          |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=101, height=56 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 101                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 56                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by willmcgugan** [comment] 2023-04-05 16:54
Suspect this is due to those keys being bound in Widget, with `show=False`.

What happens if you set `priority=True` on those bindings?

**Comment by rodrigogiraoserrao** [comment] 2023-04-05 16:56
> Suspect this is due to those keys being bound in Widget, with `show=False`.
> 
> What happens if you set `priority=True` on those bindings?

Maybe not in this MRE, but the app where I and Darren saw this issue had `priority=True`.

**Comment by davep** [comment] 2023-04-19 10:11
Seems pretty clear that this is a dupe of #2100 so I'll close this and track it via that.

**Closed by davep** 2023-04-19 10:11 UTC
Labels: bug, Task
