### ISSUE TITLE
TabPane selectable when disabled

### ISSUE THREAD

**Issue by Commandcracker** [Textualize/textual#4729] opened 2024-07-11 15:23 UTC
When a TabPane is disabled you can not switch to it but if you press below the tab name on the bar, then you can still change to the tab.

**Comment by TomJGooding** [comment] 2024-07-11 15:31
This will be fixed in the next release - see original issue #4701.

**Comment by darrenburns** [comment] 2024-07-11 15:37
Thanks for the report - as Tom said it'll be fixed soon. Closing this issue as a duplicate of #4701.

**Closed by darrenburns** 2024-07-11 15:37 UTC
