### ISSUE TITLE
Apps with nested widgets receive duplicate calls to add child widgets to the `children` `NodeList`

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1038] opened 2022-10-27 14:15 UTC
Found while working on the background code for #778, it appears that if an application is using a default screen (so, from examples, the calculator app for example), it will try and mount the widgets retrieved from `compose` more than once. On the other hand, if an app spins up its own screen on startup (so, from examples, see 5x5 for example), this doesn't happen and there is only one attempt to mount such widgets.

*Edit to add: while working through this, the understanding of what's actually going on, as well as the cause, has evolved; hence the title change of the issue.*

**Comment by davep** [comment] 2022-10-27 14:16
This is easily tested with this change to the `NodeList`:

```diff
diff --git a/src/textual/_node_list.py b/src/textual/_node_list.py
index fa5570fc..3651174f 100644
--- a/src/textual/_node_list.py
+++ b/src/textual/_node_list.py
@@ -49,6 +49,8 @@ class NodeList(Sequence):
             self._nodes.append(widget)
             self._nodes_set.add(widget)
             self._updates += 1
+        else:
+            raise Exception(f"Attempt to double append {widget!r}")

     def _remove(self, widget: Widget) -> None:
         """Remove a widget from the list.
```

**Comment by davep** [comment] 2022-10-27 14:31
To update: it's not just apps that use the default screen. This happens with 5x5 too, but in the case of 5x5 you get the exception on the way out of the app. This feels like a `App` vs `Screen` `compose` issue.

**Comment by davep** [comment] 2022-10-27 14:38
Another curiosity: `pride.py` 🏳️‍🌈  doesn't display the problem!

**Comment by davep** [comment] 2022-10-27 15:17
The core cause seems to be this: `App.mount` calls on `App._register`, which, if the widget being mounted has children, calls on `App._register` for each of the children. `App._register` itself calls `App._register_child` (the child being the widget being mounted, the parent being the parent of the widget being mounted), and `App._register_child` performs the `NoteList._append`.

Meanwhile... `Widget.__init__`, as the last thing it does, calls `Widget._add_children` which also adds the child widget to the `NodeList` (that is, adds it to the `children` of the widget being mounted).

**Comment by davep** [comment] 2022-10-27 15:59
Time to put this one aside for a moment, as it's not a blocker for #778, but is fallout from looking at that. Two things worth noting however, with 5x5 as an example.

- With the `NodeList` patch above applied, 5x5 works fine but throws the double append exception on the way out.
- With the `NodeList` patch above applied, 5x5 throws a query failed exception when inside a `watch_` method when the call to `NodeList._append` is removed from `Widget.__init__`.
- With the `NodeList` patch above applied, 5x5 throws a query failed exception when attempting to access the DOM from inside the `on_mount` of the main screen when the call to `NodeList._append` is removed from `App._register_child`.

In conversation with @willmcgugan it looks like there is a reasonable understanding of what's going wrong and how it might be improved, but it's not a showstopper right now. So, this is a record of the fault and the findings that we can come back to soon, and next week I can go back to #778.

**Comment by rodrigogiraoserrao** [comment] 2023-03-21 11:53
I confirm this is still relevant in 0.15.1.

**Comment by willmcgugan** [comment] 2023-03-21 11:57
@rodrigogiraoserrao Do you have an example that reproduces the issue, and could help me understand it?

**Comment by rodrigogiraoserrao** [comment] 2023-03-21 12:12
> @rodrigogiraoserrao Do you have an example that reproduces the issue, and could help me understand it?

I can't claim to _understand_ the issue, but I can see that some widgets are being added (at least) twice to the `NodeList`.
To see this, modify `_node_list.py::NodeList._append` to raise an exception when trying to add a widget that's already there:

```py
class NodeList(...):
    def _append(self, widget: Widget) -> None:
        """Append a Widget.

        Args:
            widget: A widget.
        """
        if widget not in self._nodes_set:
            self._nodes.append(widget)
            self._nodes_set.add(widget)
            widget_id = widget.id
            if widget_id is not None:
                self._ensure_unique_id(widget_id)
                self._nodes_by_id[widget_id] = widget
            self._updates += 1
        else:
            raise Exception("uh-oh")  # <--
```

Then, run `textual run examples/calculator.py` and see the exception be triggered.
From here, I just trusted Dave in his assessment that this was happening because of a bug that hasn't been fixed in the meantime.

**Comment by willmcgugan** [comment] 2023-03-29 11:05
I don't think this is an issue in practice. Adding a widget a second time is a NOP.

**Closed by willmcgugan** 2023-03-29 11:05 UTC
Labels: bug, Task
