### ISSUE TITLE
DataTable table row selected index mouse handling

### ISSUE THREAD

**Issue by alexveden** [Textualize/textual#1668] opened 2023-01-26 07:53 UTC
Hi, I'm working on simple DataTable app, and found that mouse selection is not handled properly.

When I click on row, the selected index changes to the previously selected row. When double-clicked the selected index changes properly.

![textual_bug](https://user-images.githubusercontent.com/18488560/214783331-39b12226-009b-434e-ad4d-c786b9ddc3e4.gif)

```python
from textual.app import App
from textual.widgets import Header, Footer
from textual.containers import Container
from textual.widgets import DataTable, ListView, ListItem, Label, Button
from textual.widget import Widget
from datetime import datetime


class TableTestApp(App):
    BINDINGS = [("d", "toggle_dark", "Toggle dark mode")]

    def compose(self):
        """Create child widgets for the app."""
        yield Header()
        yield Label('Select row', id='label')
        yield DataTable(id='data_table')
        yield Footer()

    def on_mount(self):
        table: DataTable = self.query_one('#data_table', DataTable)
        table.cursor_type = 'row'
        table.add_columns('Status', 'File', 'Log', 'Run')

        table.add_row('OK', 'my1.py', '--', 'Run')
        table.add_row('WARN', 'my2.py', '--', 'Run')
        table.add_row('ERR', 'my3.py', f"[@click=show_log('abs')]ShowLog[/]", 'Run')

    
    def on_data_table_row_selected(self, event):
         label = self.query_one('#label', Label)
         label.update(f'Row selected: {event.cursor_row}')

    def action_show_log(self, fn):
        label = self.query_one('#label', Label)
        label.update(f'Show log: {fn}')
        self.log('action_show_log')

    def action_toggle_dark(self) -> None:
        """An action to toggle dark mode."""
        self.dark = not self.dark

if __name__ == "__main__":
    #print("Hello world")
    app = TableTestApp()
    app.run()
```

**Comment by rodrigogiraoserrao** [comment] 2023-03-21 14:42
Hey there!
This issue seems to have been fixed somewhere along the way, as I cannot reproduce this with 0.15.1.
Therefore, I am closing this issue.
Thanks! :D

**Closed by rodrigogiraoserrao** 2023-03-21 14:42 UTC
