### ISSUE TITLE
Docs: Screen Example not fully functional

### ISSUE THREAD

**Issue by lovetox** [Textualize/textual#1767] opened 2023-02-11 13:17 UTC
Textual Version: 0.10.1

The screens docs at https://textual.textualize.io/guide/screens/

provides an example of a modal dialog implemented with a screen.

When i copy paste the last example on the page, hit Quit, and on the following modal dialog hit "Cancel", im not able to invoke the modal dialog again.

I dont know if this is a bug with the example or the lib itself.

**Comment by davep** [comment] 2023-02-11 13:49
Thanks. Looks to be a duplicate of #1733 -- it's fixed for the next release.

**Closed by davep** 2023-02-11 13:49 UTC
