### ISSUE TITLE
Errors in compose should not be silently ignored

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1370] opened 2022-12-15 14:16 UTC
Errors in a widget's `compose` method are written to stdout, but otherwise ignored and the app runs.

Such errors should exit the app with a pretty traceback. Here's an example that demonstrates the issue:

```python
from textual.app import App, ComposeResult
from textual.widget import Widget


class Broken(Widget):
    def compose(self) -> ComposeResult:
        1/0


class MyApp(App):
    def compose(self) -> ComposeResult:
        yield Widget(Broken())


app = MyApp()
app.run()
```

**Comment by WMRamadan** [comment] 2022-12-17 02:05
@willmcgugan What would the label for this be?

**Comment by davep** [comment] 2023-01-04 15:17
Duplicate of #1177 perhaps? And potentially related to #1194 too.

**Closed** 2023-01-06 16:42 UTC
