### ISSUE TITLE
Unclosed event loop with easing example

### ISSUE THREAD

**Issue by sanders41** [Textualize/textual#127] opened 2021-10-01 01:19 UTC
Every time I close the [easing example](https://github.com/willmcgugan/textual/blob/main/examples/easing.py). I get the following error:

```sh
/usr/lib/python3.9/asyncio/base_events.py:681: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
I am thinking there are still messages processing at shutdown that are keeping the loop running, but I have not been able to track down the root cause yet. 

Possibly a similar issue to #82?

OS: Manjaro Linux 21.1.4

**Comment by willmcgugan** [comment] 2021-10-01 08:15
Interesting. I don't see that, probably because I develop with 3.7. Shutting down cleanly is one of the hardest things about asyncio.

**Comment by sanders41** [comment] 2021-10-01 12:18
I tested 3.7 and am seeing the error there also. I tried it out on my Mac, and there it seems to be random. Sometimes I get the error and sometimes I don't with 3.7, 3.8, and 3.9.

**Comment by willmcgugan** [comment] 2021-10-01 12:21
Are you certain you are running the latest code? What does `pip freeze | grep textual` give you?

It has very possibly reoccured, but I had fixed a very similar issue a while back.

**Comment by sanders41** [comment] 2021-10-01 12:26
I'm running from my fork. I tried pull upstream and then a fresh `poetry install`, but am still seeing the error. Do I need to do a separate install to run the examples?

**Comment by willmcgugan** [comment] 2021-10-01 12:30
Try uninstalling textual first, but I would have thought that would be enough.

So you are seeing this on Linux consistently, but MacOS intermittently?

**Comment by sanders41** [comment] 2021-10-01 12:44
I tried deleting poetry's virtual environment and re-creating it, but no difference.

Correct, I am getting the error every time on Linux, but only intermittently on MacOS. I'll keep doing some testing to see if I can get any more information.

**Comment by lllama** [comment] 2021-10-01 20:37
Not that I know what I'm talking about but there was a [good talk at EuroPython a few years ago](https://www.youtube.com/watch?v=1lJDZx6f6tY) that talked about asyncio things, including shutting down gracefully.

**Comment by pom11** [comment] 2022-01-07 19:42
<img width="653" alt="Screenshot 2022-01-07 at 21 39 49" src="https://user-images.githubusercontent.com/60760299/148597963-dbe1353c-a150-454e-8bd5-03eca3fc7064.png">

i get the same error when trying to get docker container status

- textual 0.1.13
- docker 5.0.3
- python 3.8.10

```python
class Container(Widget):

	mouse_over = Reactive(False)

	def __init__(self, id: str = None):
		super().__init__(id=id)
		self.id = id

	def container(self):
		try:
			client = docker.from_env()
			container = client.containers.get(self.id)
			status = container.status()
			return status
		except Exception as e:
			return "Error"

	def on_mount(self):
		self.set_interval(1, self.refresh)

	def render(self):
		data = self.container()
		return Panel(data, style=("on red" if self.mouse_over else ""))
```

**Comment by DrBenton** [comment] 2022-05-04 09:58
I can indeed reproduce the bug (on Ubuntu).
 - Python 3.8.13: the `asyncio/base_events.py:686: ResourceWarning: unclosed event loop` error is displayed in the background of the Textual display, when the easing example is launched - :warning: however it doesn't happen when `uvloop` is installed.
     ![Screenshot from 2022-05-04 10-55-21](https://user-images.githubusercontent.com/722388/166660533-1c569b5e-9ddf-4b57-91b2-d14d8f189992.png)

 - Python 3.9.12: it is displayed when we exit the app with Ctrl+C - :warning: however it doesn't happen when `uvloop` is installed.

I'm going to take a look at this! :slightly_smiling_face:

**Comment by darrenburns** [comment] 2022-05-04 12:21
@DrBenton There is an open PR above for this ^ Although I thought this wasn't an issue on the `css` branch

**Comment by DrBenton** [comment] 2022-05-11 10:07
Status update: the bug seems to be fixed on the `css` branch, where the current Textual development is taking place. So hopefully it will no longer be visible when this branch will be merged to `main` :slightly_smiling_face:  :crossed_fingers:

**Comment by willmcgugan** [comment] 2022-10-25 09:20
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue

**Closed by willmcgugan** 2022-10-25 09:20 UTC
Labels: bug
