### ISSUE TITLE
DataTable height: auto; does not account for horizontal scrollbar.

### ISSUE THREAD

**Issue by aaronst** [Textualize/textual#1289] opened 2022-11-25 20:00 UTC
This example creates a `DataTable` with a `height` of `2`, but I think it should be `3` (header, row, and horizontal scrollbar).

```python
from textual.app import App, ComposeResult
from textual.widgets import DataTable


class Test(App):
    DEFAULT_CSS = """
    DataTable {
        height: auto;
    }
    """

    def compose(self) -> ComposeResult:
        yield DataTable(id="table")

    def on_mount(self) -> None:
        table = self.get_child_by_id("table", DataTable)
        table.add_column("test")
        table.add_row("a" * 200)


Test().run()
```

**Comment by aaronst** [comment] 2022-11-25 20:03
I've been getting around this with `min-height: 3;`.

**Comment by willmcgugan** [comment] 2023-01-04 14:04
I'm not convinced this should be the case. It means the datatable widget will have to change its dimensions based on the visibility of the scrollbar. 

I think in these circumstances you are better off setting the scrollbar to always visible

**Comment by davep** [comment] 2023-08-24 19:56
Closing as working as intended.

https://label.dev/wontfix/

**Closed by davep** 2023-08-24 19:56 UTC
