### ISSUE TITLE
Add a way to load a new directory in DirectoryTree

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2448] opened 2023-05-01 15:57 UTC
- We need a way to change the directory root (and refresh) a DirectoryTree. 
- Related: we need a way to refresh the current directory.
- We have a `load_directory` method, which I think should be private.

**Comment by davep** [comment] 2023-05-01 19:01
This is pretty much a duplicate of #2056

**Comment by davep** [comment] 2023-05-03 08:42
Making a note of part of a conversation yesterday: for the moment the "refresh" will be for the `DirectoryTree` as a whole. Ideally we'd like to add the ability to refresh an individual directory within the tree. To do that, however, `Tree` itself will need to be updated to allow for a node's children to be removed (and, indeed, it would be useful if `Tree` supported node removal).

**Closed** 2023-05-03 11:15 UTC
Labels: enhancement, Task
