### ISSUE TITLE
Bindings inside apps are not combinied

### ISSUE THREAD

**Issue by mohammad-sayed-ahmad** [Textualize/textual#3693] opened 2023-11-16 15:03 UTC
Hello,
I have a dual language keyboard(Arabic/English) and I have noticed that when using 'BINDINGS' inside apps, bindings work only using the English keyboard mode when capslock is off. I am still new to textual but it seems mostly unhelpful to seperate each key from characters. Maybe you could add an extra option allowing you to toggle between character as typed and character as pressed.

```py
class TestApp(App):
    BINDINGS = [
        Binding(key='d', action="toggle_dark_mode", description="Toggle Dark Mode")
    ]
    def compose(self):
        yield Header(show_clock=True)
        yield Footer()

    def action_toggle_dark_mode(self):
        self.dark = not self.dark
```

**Comment by TomJGooding** [comment] 2023-11-16 15:28
Could you try running `textual keys` (available from the Textual [devtools](https://textual.textualize.io/guide/devtools/)) and see what keys turn up from your terminal?

It might also be helpful if you run `textual diagnose` and paste the results.

**Comment by rodrigogiraoserrao** [comment] 2023-11-16 17:03
Hey Mohammad, thanks for opening this issue!

<kbd>d</kbd> and <kbd>Shift</kbd>+<kbd>d</kbd> are effectively different key combinations and that's why pressing <kbd>d</kbd> while <kbd>CapsLock</kbd> is on won't trigger the binding for <kbd>d</kbd>.

I understand this might not have been what you expected.
If you wish, you can easily extend your `BINDINGS` to duplicate all letter bindings so that they work like you expected.
Feel free to head on [to the Discord server](https://discord.gg/Enf6Z3qhVr) if you need help implementing the change I suggested above.

I'm closing this issue as this is not a bug, it is expected behaviour, and we wish to keep distinguishing between <kbd>d</kbd> and <kbd>Shift</kbd>+<kbd>d</kbd>.

**Closed by rodrigogiraoserrao** 2023-11-16 17:03 UTC

**Comment by rodrigogiraoserrao** [comment] 2023-11-16 17:06
As far as the Arabic keyboard is concerned, the experiment of running `textual keys` like Tom suggests above will show you that we (read, Textual) can't really tell _what_ key is being pressed, we can only try to guess.
Thus, if you have your keyboard in Arabic, it is likely that pressing the key that would produce a `d` in English will be producing something quite different from a `d`, meaning we won't be able to trigger the keybinding that you expected to be triggered.
