### ISSUE TITLE
Suggester docs

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#5030] opened 2024-09-21 17:42 UTC
There doesn't seem to be any documentation of Suggesters on the Input page. Just a link to the API page.

Suggest we add a section with a small example to cover that.

**Comment by TomJGooding** [comment] 2024-09-21 17:51
Duplicate of #4934?

**Comment by willmcgugan** [comment] 2024-09-21 18:13
So it is!

**Closed** 2024-09-21 19:04 UTC
