### ISSUE TITLE
Error/stack trace when adding a new snapshot test

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2915] opened 2023-07-11 14:39 UTC
When adding a new snapshot test, without having first done an update of the snapshots, a `make test` results in the following. Perhaps I'm misremembering but didn't this used to result in an informative error, telling you that you needed to refresh the snapshots?

```
Traceback (most recent call last):
  File "/Users/davep/develop/python/textual/.venv/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 189, in console_main
    code = main()
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/_pytest/config/__init__.py", line 167, in main
    config=config
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/_pytest/main.py", line 317, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/_pytest/main.py", line 270, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_hooks.py", line 433, in __call__
    return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_manager.py", line 112, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_callers.py", line 133, in _multicall
    teardown[0].send(outcome)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/_pytest/terminal.py", line 857, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_result.py", line 108, in get_result
    raise exc.with_traceback(exc.__traceback__)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pluggy/_callers.py", line 80, in _multicall
    res = hook_impl.function(*args)
  File "/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/pytest_textual_snapshot.py", line 165, in pytest_sessionfinish
    template = Template(snapshot_template_path.read_text())
  File "/Users/davep/.pyenv/versions/3.7.13/lib/python3.7/pathlib.py", line 1221, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/Users/davep/.pyenv/versions/3.7.13/lib/python3.7/pathlib.py", line 1208, in open
    opener=self._opener)
  File "/Users/davep/.pyenv/versions/3.7.13/lib/python3.7/pathlib.py", line 1063, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/davep/develop/python/textual/.venv/lib/python3.7/site-packages/resources/snapshot_report_template.jinja2'
make: *** [test] Error 1
```

**Comment by willmcgugan** [comment] 2023-07-11 15:07
@darrenburns One for you I think...

**Comment by darrenburns** [comment] 2023-07-12 09:22
Fixed in https://github.com/Textualize/pytest-textual-snapshot/pull/1

This'll require a release @willmcgugan.

**Comment by davep** [comment] 2023-07-12 09:59
Thanks @darrenburns -- I was just going to point out that the same thing happens if a snapshot differs too, but I imagine it's all the same root cause?

**Comment by darrenburns** [comment] 2023-07-12 10:01
Yep, same root cause. It just couldn't find the path of the Jinja HTML template, which gets rendered both when a snapshot differs, and when there's a new snapshot.

**Closed** 2023-07-12 10:01 UTC
Labels: Task
